title: Look-n-Trace app
author: OVM SOFT
theme: minima
description: Look-n-Trace helps you draw by tracing any image through your camera. Pick an image, adjust its opacity, and trace what you see on paper.

# 2.5.2 (2024)
remote_theme: jekyll/minima@c6e74bb

header_pages:
    - about.md
    - issues.md
    - privacy.md
    - support.md

